// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"Description,omitempty"`
	Courses     []*Course `json:"Courses"`
}

type Course struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"Description,omitempty"`
	Category    *Category `json:"Category"`
}

type Mutation struct {
}

type NewCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"Description,omitempty"`
}

type NewCourse struct {
	Name        string  `json:"name"`
	Description *string `json:"Description,omitempty"`
	CategoryID  string  `json:"CategoryId"`
}

type Query struct {
}
